server:
  port: ${SERVER_PORT:9090}

spring:
  application:
    name: digital-signature-system

  profiles:
    include: ${SPRING_PROFILES_INCLUDE:datasource}

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB

app:
  master-key: ${MASTER_KEY:q50cdH2AnbvEuWqt7Q3E9kItfia9OSU3nV9pHWHWw4E=}

cron:
  rotate-time: ${ROTATE_TIME:0 0 3 1 * *} #every month at 3:00 AM